[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
greenmove = "36D7U8McCLZF9ahuGmoiXehXzFLFm6v8N1gQVAfricSY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
