[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
greenmove = "6iKNyZGH5CNddXFYmeNniZbeQM74iCsRHHDsW5DHzxaJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
